name: pipeline
'on':
  push: null
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Maven test
        run: mvn test
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{steps.jacoco.outputs.coverage}}"
          echo "branch coverage = ${{steps.jacoco.outputs.branches}}"
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Package
        run: mvn package
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
      - name: Publish package
        run: |
          echo "publicando o artefato"
  deploy-STG:
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: stage
        shell: bash
        run: |
          echo "Deploy STG"

  smoketest:
    runs-on: ubuntu-latest
    needs: deploy-STG
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: checkout
        shell: bash
        run: |
          echo 'smoke test'
        
        
             
  
  deploy-Pre:
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/release'
    steps:
      - name: pre
        shell: bash
        run: |
          echo "Deploy PRE"
  deploy-Prod:
    runs-on: ubuntu-latest
    needs: publish
    if: github.ref == 'refs/heads/main'
    steps:
      - name: prod
        shell: bash
        run: |
          echo "Deploy PROD"
